language: android
jdk: oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.1
    - android-25
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-google_play_services
    - addon-google_apis-google-25

addons:
  sonarcloud:
    organization: "amrabed-github"

script:
  - sonar-scanner
